// Realistic demo content for Dream$ MVP feed
// Uses free video/image sources with caption-content alignment

export interface DemoPost {
  id: string;
  creatorId: string;
  creator: string;
  avatar: string;
  caption: string;
  mediaUrl: string;
  mediaType: 'image' | 'video';
  category: string;
  likes: number;
  comments: number;
  shares: number;
  views: number;
  isEligible: boolean;
  eligibleAmount: number;
}

// Short free-to-use video URLs (Pexels/Pixabay-sourced CDN)
const VIDEOS = {
  lagosCity: 'https://videos.pexels.com/video-files/5765294/5765294-sd_360_640_25fps.mp4',
  cooking: 'https://videos.pexels.com/video-files/3195394/3195394-sd_360_640_25fps.mp4',
  dancing: 'https://videos.pexels.com/video-files/5319984/5319984-sd_360_640_25fps.mp4',
  coding: 'https://videos.pexels.com/video-files/5483075/5483075-sd_360_640_25fps.mp4',
  fitness: 'https://videos.pexels.com/video-files/4057411/4057411-sd_360_640_25fps.mp4',
  fashion: 'https://videos.pexels.com/video-files/6567583/6567583-sd_360_640_25fps.mp4',
  sunset: 'https://videos.pexels.com/video-files/1409899/1409899-sd_640_360_25fps.mp4',
  food: 'https://videos.pexels.com/video-files/3296396/3296396-sd_360_640_25fps.mp4',
  music: 'https://videos.pexels.com/video-files/3571264/3571264-sd_360_640_25fps.mp4',
  street: 'https://videos.pexels.com/video-files/4489032/4489032-sd_360_640_25fps.mp4',
  beauty: 'https://videos.pexels.com/video-files/6149832/6149832-sd_360_640_25fps.mp4',
  travel: 'https://videos.pexels.com/video-files/3015510/3015510-sd_640_360_25fps.mp4',
  pet: 'https://videos.pexels.com/video-files/4588441/4588441-sd_360_640_25fps.mp4',
  art: 'https://videos.pexels.com/video-files/5765285/5765285-sd_360_640_25fps.mp4',
  nature: 'https://videos.pexels.com/video-files/3571264/3571264-sd_360_640_25fps.mp4',
};

// Caption-aligned images (Unsplash-sourced with relevant keywords)
const IMAGES = {
  lagosNight: 'https://images.unsplash.com/photo-1618828665011-0abd1b3e9a29?w=800&h=1200&fit=crop',
  jollofRice: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=800&h=1200&fit=crop',
  africanFashion: 'https://images.unsplash.com/photo-1590735213920-68192a487bc2?w=800&h=1200&fit=crop',
  motivation: 'https://images.unsplash.com/photo-1493836512294-502baa1986e2?w=800&h=1200&fit=crop',
  techSetup: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&h=1200&fit=crop',
  workout: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&h=1200&fit=crop',
  africanFood: 'https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=800&h=1200&fit=crop',
  braids: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&h=1200&fit=crop',
  beach: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=1200&fit=crop',
  gaming: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&h=1200&fit=crop',
};

export const realisticDemoPosts: DemoPost[] = [
  // === VIDEO POSTS (primary) ===
  {
    id: 'demo-v1',
    creatorId: 'u1',
    creator: 'chioma_vibes',
    avatar: 'CV',
    caption: 'Lagos nightlife hits different 🌃✨ The city comes alive after dark with lights, music, and energy everywhere.',
    mediaUrl: VIDEOS.lagosCity,
    mediaType: 'video',
    category: 'Lifestyle',
    likes: 12400,
    comments: 89,
    shares: 234,
    views: 124000,
    isEligible: true,
    eligibleAmount: 15,
  },
  {
    id: 'demo-v2',
    creatorId: 'u3',
    creator: 'amaka_cooks',
    avatar: 'AC',
    caption: 'Jollof rice recipe that slaps 🍚🔥 Secret ingredient is patience and love! Full recipe in bio.',
    mediaUrl: VIDEOS.cooking,
    mediaType: 'video',
    category: 'Food',
    likes: 8900,
    comments: 234,
    shares: 189,
    views: 89000,
    isEligible: false,
    eligibleAmount: 0,
  },
  {
    id: 'demo-v3',
    creatorId: 'u4',
    creator: 'dance_king_ng',
    avatar: 'DK',
    caption: 'New Afrobeats challenge 🕺💥 Can you hit these moves? Drop your video using #DanceKingChallenge!',
    mediaUrl: VIDEOS.dancing,
    mediaType: 'video',
    category: 'Dance',
    likes: 67800,
    comments: 1230,
    shares: 2341,
    views: 678000,
    isEligible: true,
    eligibleAmount: 20,
  },
  {
    id: 'demo-v4',
    creatorId: 'u26',
    creator: 'tech_sis',
    avatar: 'TS',
    caption: 'Coding tutorial for beginners 💻 From zero to hero in Python. Start your tech journey today!',
    mediaUrl: VIDEOS.coding,
    mediaType: 'video',
    category: 'Tech',
    likes: 18900,
    comments: 456,
    shares: 890,
    views: 189000,
    isEligible: true,
    eligibleAmount: 10,
  },
  {
    id: 'demo-v5',
    creatorId: 'u23',
    creator: 'fit_naija_boy',
    avatar: 'FN',
    caption: 'No gym? No problem 💪🏾 Home workout routine that builds real muscle. 30 mins a day is all you need!',
    mediaUrl: VIDEOS.fitness,
    mediaType: 'video',
    category: 'Sports',
    likes: 42000,
    comments: 678,
    shares: 2100,
    views: 420000,
    isEligible: true,
    eligibleAmount: 10,
  },
  {
    id: 'demo-v6',
    creatorId: 'u27',
    creator: 'fashion_plug_ng',
    avatar: 'FP',
    caption: 'Ankara collection 2025 🧵✨ Fresh designs that blend tradition with modern style. DM for orders!',
    mediaUrl: VIDEOS.fashion,
    mediaType: 'video',
    category: 'Fashion',
    likes: 45000,
    comments: 890,
    shares: 2300,
    views: 450000,
    isEligible: false,
    eligibleAmount: 0,
  },
  {
    id: 'demo-v7',
    creatorId: 'u24',
    creator: 'abuja_foodie',
    avatar: 'AF',
    caption: 'Best suya spots in Wuse 2 🍖🔥 After trying 20+ places, these are my top 3. You need to try them!',
    mediaUrl: VIDEOS.food,
    mediaType: 'video',
    category: 'Food',
    likes: 15600,
    comments: 345,
    shares: 780,
    views: 156000,
    isEligible: true,
    eligibleAmount: 15,
  },
  {
    id: 'demo-v8',
    creatorId: 'u25',
    creator: 'music_maestro',
    avatar: 'MM',
    caption: 'New track dropping Friday 🎵🔥 Been cooking this one for 6 months. Pre-save link in bio!',
    mediaUrl: VIDEOS.music,
    mediaType: 'video',
    category: 'Music',
    likes: 67000,
    comments: 2340,
    shares: 4500,
    views: 670000,
    isEligible: true,
    eligibleAmount: 20,
  },
  {
    id: 'demo-v9',
    creatorId: 'u37',
    creator: 'street_food_ng',
    avatar: 'SF',
    caption: 'Best akara spots in Lagos 🍳 Golden, crispy, and perfectly spiced. Where\'s your favorite spot?',
    mediaUrl: VIDEOS.street,
    mediaType: 'video',
    category: 'Food',
    likes: 23000,
    comments: 567,
    shares: 1200,
    views: 230000,
    isEligible: true,
    eligibleAmount: 10,
  },
  {
    id: 'demo-v10',
    creatorId: 'u22',
    creator: 'makeup_by_funke',
    avatar: 'MF',
    caption: 'Wedding guest look under ₦5k 💄✨ Proving you can slay on a budget! All products linked in bio.',
    mediaUrl: VIDEOS.beauty,
    mediaType: 'video',
    category: 'Lifestyle',
    likes: 28000,
    comments: 456,
    shares: 1200,
    views: 280000,
    isEligible: false,
    eligibleAmount: 0,
  },
  {
    id: 'demo-v11',
    creatorId: 'u28',
    creator: 'travel_ng_',
    avatar: 'TN',
    caption: 'Hidden beach in Calabar you need to visit 🏖️ Crystal clear waters and zero crowd. Perfect weekend escape!',
    mediaUrl: VIDEOS.travel,
    mediaType: 'video',
    category: 'Lifestyle',
    likes: 56000,
    comments: 890,
    shares: 5600,
    views: 560000,
    isEligible: true,
    eligibleAmount: 20,
  },
  {
    id: 'demo-v12',
    creatorId: 'u33',
    creator: 'pet_lover_ng',
    avatar: 'PL',
    caption: 'My dog does the funniest things 🐕😂 Caught him stealing food again! Pet owners, you know the struggle.',
    mediaUrl: VIDEOS.pet,
    mediaType: 'video',
    category: 'Entertainment',
    likes: 45000,
    comments: 678,
    shares: 3400,
    views: 450000,
    isEligible: true,
    eligibleAmount: 10,
  },
  {
    id: 'demo-v13',
    creatorId: 'u36',
    creator: 'nollywood_bts',
    avatar: 'NB',
    caption: 'Behind the scenes of your favorite movie 🎬 The magic happens off-camera! Swipe to see more.',
    mediaUrl: VIDEOS.art,
    mediaType: 'video',
    category: 'Entertainment',
    likes: 78000,
    comments: 1230,
    shares: 5600,
    views: 780000,
    isEligible: true,
    eligibleAmount: 15,
  },
  {
    id: 'demo-v14',
    creatorId: 'u20',
    creator: 'naija_comedy_king',
    avatar: 'NC',
    caption: 'When your mama catches you sneaking out 😂💀 Every Nigerian kid knows this fear! Tag someone who can relate.',
    mediaUrl: VIDEOS.nature,
    mediaType: 'video',
    category: 'Comedy',
    likes: 156000,
    comments: 4560,
    shares: 8500,
    views: 1560000,
    isEligible: true,
    eligibleAmount: 20,
  },
  {
    id: 'demo-v15',
    creatorId: 'u21',
    creator: 'lagos_traffic_tales',
    avatar: 'LT',
    caption: 'Third Mainland at 6am vs 6pm 🚗😩 The bridge never sleeps, and neither do we in this traffic!',
    mediaUrl: VIDEOS.lagosCity,
    mediaType: 'video',
    category: 'Lifestyle',
    likes: 34000,
    comments: 678,
    shares: 890,
    views: 340000,
    isEligible: true,
    eligibleAmount: 15,
  },
  // === IMAGE POSTS (mix in) ===
  {
    id: 'demo-i1',
    creatorId: 'u2',
    creator: 'tech_adebayo',
    avatar: 'TA',
    caption: 'How I made my first ₦100k online 💰 Started with zero, now helping others do the same. Hard work pays!',
    mediaUrl: IMAGES.techSetup,
    mediaType: 'image',
    category: 'Tech',
    likes: 45200,
    comments: 890,
    shares: 1203,
    views: 452000,
    isEligible: true,
    eligibleAmount: 20,
  },
  {
    id: 'demo-i2',
    creatorId: 'u5',
    creator: 'unilag_babe',
    avatar: 'UB',
    caption: 'Day in my life as a final year student 📚✨ From morning lectures to late night studying. The grind is real!',
    mediaUrl: IMAGES.motivation,
    mediaType: 'image',
    category: 'Education',
    likes: 5600,
    comments: 123,
    shares: 89,
    views: 56000,
    isEligible: false,
    eligibleAmount: 0,
  },
  {
    id: 'demo-i3',
    creatorId: 'u11',
    creator: 'style_queen',
    avatar: 'SQ',
    caption: 'Ankara styles for every occasion 👗✨ From casual to formal, there\'s an Ankara look for everything!',
    mediaUrl: IMAGES.africanFashion,
    mediaType: 'image',
    category: 'Fashion',
    likes: 78900,
    comments: 1560,
    shares: 5678,
    views: 789000,
    isEligible: false,
    eligibleAmount: 0,
  },
  {
    id: 'demo-i4',
    creatorId: 'u38',
    creator: 'naija_motivation',
    avatar: 'NM',
    caption: 'Your breakthrough is coming 🙏🏾 Keep pushing, keep praying, keep working. Your time will come!',
    mediaUrl: IMAGES.motivation,
    mediaType: 'image',
    category: 'Lifestyle',
    likes: 156000,
    comments: 3450,
    shares: 12000,
    views: 1560000,
    isEligible: false,
    eligibleAmount: 0,
  },
  {
    id: 'demo-i5',
    creatorId: 'u10',
    creator: 'fit_naija',
    avatar: 'FN',
    caption: 'Home workout that burns 500 calories 🔥💪 No equipment needed, just determination. Let\'s go!',
    mediaUrl: IMAGES.workout,
    mediaType: 'image',
    category: 'Sports',
    likes: 42300,
    comments: 890,
    shares: 2345,
    views: 423000,
    isEligible: true,
    eligibleAmount: 10,
  },
  {
    id: 'demo-i6',
    creatorId: 'u35',
    creator: 'game_reviews_ng',
    avatar: 'GR',
    caption: 'FIFA 25 review - Worth it? 🎮 After 100+ hours of gameplay, here\'s my honest take on the new game.',
    mediaUrl: IMAGES.gaming,
    mediaType: 'image',
    category: 'Entertainment',
    likes: 28000,
    comments: 567,
    shares: 1800,
    views: 280000,
    isEligible: true,
    eligibleAmount: 20,
  },
  {
    id: 'demo-i7',
    creatorId: 'u31',
    creator: 'hair_by_nkechi',
    avatar: 'HN',
    caption: 'Knotless braids tutorial 💇🏾‍♀️ Learn how to achieve salon-quality braids at home. Save your money!',
    mediaUrl: IMAGES.braids,
    mediaType: 'image',
    category: 'Lifestyle',
    likes: 67000,
    comments: 1230,
    shares: 4500,
    views: 670000,
    isEligible: false,
    eligibleAmount: 0,
  },
  {
    id: 'demo-i8',
    creatorId: 'u29',
    creator: 'crypto_naija',
    avatar: 'CN',
    caption: 'Bitcoin basics for Nigerians 💰 Understanding crypto doesn\'t have to be complicated. Start here!',
    mediaUrl: IMAGES.techSetup,
    mediaType: 'image',
    category: 'Tech',
    likes: 34000,
    comments: 678,
    shares: 2100,
    views: 340000,
    isEligible: true,
    eligibleAmount: 20,
  },
  {
    id: 'demo-i9',
    creatorId: 'u9',
    creator: 'travel_ng',
    avatar: 'TN',
    caption: 'Hidden gems in Nigeria you need to visit 🌴 From waterfalls to mountains - explore your country first!',
    mediaUrl: IMAGES.beach,
    mediaType: 'image',
    category: 'Lifestyle',
    likes: 56700,
    comments: 890,
    shares: 4532,
    views: 567000,
    isEligible: true,
    eligibleAmount: 15,
  },
  {
    id: 'demo-i10',
    creatorId: 'u30',
    creator: 'small_chops_queen',
    avatar: 'SC',
    caption: 'Puff puff recipe from scratch 🍩 Fluffy, golden, and perfectly sweet. Your guests will love these!',
    mediaUrl: IMAGES.africanFood,
    mediaType: 'image',
    category: 'Food',
    likes: 23000,
    comments: 456,
    shares: 1200,
    views: 230000,
    isEligible: true,
    eligibleAmount: 10,
  },
];
